// Login
export const GET_LOGIN_REQUESTED = "GET_LOGIN_REQUESTED";
export const GET_LOGIN_SUCCESS = "GET_LOGIN_SUCCESS";


//Modules
export const GET_MODULES_REQUESTED = "GET_MODULES_REQUESTED";
export const GET_MODULES_SUCCESS = "GET_MODULES_SUCCESS";
export const MODULES_FAILED = "MODULES_FAILED";
